Repository elastic/opentelemetry, pull requests merged in 2025-07, with the labels that each got.

#288 Add EDOT CF AWS documentation
  docs/docset.yml
  docs/reference/_snippets/serverless-endpoint-api.md
  docs/reference/edot-cloud-forwarder/aws.md
  docs/reference/edot-cloud-forwarder/index.md
  docs/reference/index.md
  docs/reference/quickstart/serverless/docker.md
  docs/reference/quickstart/serverless/hosts_vms.md
  docs/reference/quickstart/serverless/index.md
  docs/reference/quickstart/serverless/k8s.md
  docs/reference/toc.yml
Labels: documentation

#244 Import iOS and Android documentation
  docs/reference/compatibility/nomenclature.md
  docs/reference/edot-collector/config/configure-metrics-collection.md
  docs/reference/edot-sdks/android/automatic-instrumentation.md
  docs/reference/edot-sdks/android/configuration.md
  docs/reference/edot-sdks/android/getting-started.md
  docs/reference/edot-sdks/android/images/dynamic-config.svg
  docs/reference/edot-sdks/android/images/find-export-endpoint/1.png
  docs/reference/edot-sdks/android/images/find-export-endpoint/2.png
  docs/reference/edot-sdks/android/images/find-export-endpoint/3.png
  docs/reference/edot-sdks/android/images/find-export-endpoint/4.png
  docs/reference/edot-sdks/android/images/intro/distributed-tracing.png
  docs/reference/edot-sdks/android/images/opentelemetry-logo.png
  docs/reference/edot-sdks/android/images/span-visualization/1.png
  docs/reference/edot-sdks/android/images/span-visualization/2.png
  docs/reference/edot-sdks/android/images/span-visualization/3.png
  docs/reference/edot-sdks/android/index.md
  docs/reference/edot-sdks/android/manual-instrumentation.md
  docs/reference/edot-sdks/android/troubleshooting.md
  docs/reference/edot-sdks/index.md
  docs/reference/edot-sdks/ios/configuration.md
  docs/reference/edot-sdks/ios/dynamic-config.svg
  docs/reference/edot-sdks/ios/images/dynamic-config.svg
  docs/reference/edot-sdks/ios/index.md
  docs/reference/edot-sdks/ios/instrumentation.md
  docs/reference/edot-sdks/ios/set-up-apm-ios-agent.md
  docs/reference/edot-sdks/ios/supported-technologies.md
  docs/reference/edot-sdks/python/setup/index.md
  docs/reference/toc.yml
Labels: documentation

#340 Edit links
  docs/reference/index.md
Labels: bug

#341 Fix more links
  .gitignore
  docs/reference/compatibility/sdks.md
  docs/reference/edot-sdks/android/automatic-instrumentation.md
Labels: documentation

#374 OpAMP documentation for EDOT PHP
  docs/reference/edot-sdks/php/configuration.md
Labels: documentation

#377 Update configuration.md
  docs/reference/edot-sdks/php/configuration.md
Labels: documentation

#365 Replace versions and remove update script
  .github/workflows/updatecli.yml
  docs/docset.yml
  docs/reference/edot-collector/config/default-config-standalone.md
  docs/reference/edot-collector/download.md
  docs/reference/edot-sdks/java/setup/runtime-attach.md
  docs/reference/index.md
  docs/reference/quickstart/ech/docker.md
  docs/reference/quickstart/ech/k8s.md
  docs/reference/quickstart/self-managed/docker.md
  docs/reference/quickstart/self-managed/k8s.md
  docs/reference/quickstart/serverless/docker.md
  docs/reference/quickstart/serverless/k8s.md
  docs/reference/use-cases/kubernetes/customization.md
  docs/reference/use-cases/kubernetes/deployment.md
  docs/reference/use-cases/kubernetes/instrumenting-applications.md
  docs/reference/use-cases/kubernetes/prerequisites-compatibility.md
  docs/reference/use-cases/kubernetes/upgrade.md
  updatecli/updatecli.d/versions.yml
  updatecli/values.d/scm.yml
Labels: blocked
